version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../monitoring/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    volumes:
      - ../monitoring/loki:/etc/loki
    command:
      - --config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ../monitoring/promtail:/etc/promtail
      - /var/log:/var/log:ro
    command:
      - --config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ../monitoring/tempo:/etc/tempo
    command:
      - --config.file=/etc/tempo/tempo-config.yaml
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:latest
    volumes:
      - ../monitoring/blackbox:/etc/blackbox_exporter
    command:
      - --config.file=/etc/blackbox_exporter/blackbox.yml
    networks:
      - monitoring

  item-db:
    image: postgres:15
    container_name: item-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: item
    ports:
      - "5432:5432"
    volumes:
      - item-db-data:/var/lib/postgresql/data
    networks:
      - monitoring
    labels:
      - "traefik.enable=false"
      - "prometheus.scrape=true"
      - "prometheus.port=5432"
      - "prometheus.path=/metrics"

networks:
  traefik:
  monitoring:

volumes:
  item-db-data:
